### PR TITLE
FIX: Import in Row.ts

### LINKED ISSUE #10: tsc "Can't find RowData"
Hi, while trying to transpile with tsc I get this error.

``` 
node_modules/embed-table/dist/structures/Row.d.ts:1:25 - error TS2307: Cannot find module 'index.js' or its corresponding type declarations.

1 import { RowData } from 'index.js';
                          ~~~~~~~~~~
```
image

Using:
- embed-table@4.2.2
- node@18.15.0

### PR DESCRIPTION
**Pull request by Uriei**
Fixes #10

### CODE REVIEW

**Review by Fyrlex — CHANGES_REQUESTED** [review]
Hey! Thanks for catching this issue. If you wouldn't mind adding the .js extension to the path, that would be great!

**Comment by Uriei** [comment]
Done.

**Comment by Fyrlex** [comment]
Unfortunately I am on vacation and cannot publish this to npm at this time, but you should be able to install the package using the URL to this repo. A colleague will update it when they are online later today. Thanks again!

**Comment by Uriei** [comment]
No hurry, in the end I'm not going to use this package for what I wanted as
I would need more than 25 fields for the table and discord won't allow it.
Thanks anyways!

**Comment by Fyrlex** [comment]
The alternative to the fields is to use the toString method and insert it into your embed's description.

**Pull request merged**
